version: "3.8"

networks:
  wazuh-net:
    driver: overlay
    attachable: true

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.0
    networks:
      wazuh-net:
        aliases:
          - wazuh.indexer          # <-- CRITICAL: gives DNS name dashboard expects
    deploy:
      replicas: 1

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    networks:
      - wazuh-net
    deploy:
      replicas: 1

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    ports:
      - "443:5601"
    networks:
      - wazuh-net
    deploy:
      replicas: 1
