# stack/wazuh-stack-test.yml
version: "3.8"

networks:
  soc:
    driver: overlay
    attachable: true   # so `docker run --network <stack>_soc` works

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:

services:
  wazuh-indexer:
    image: "wazuh/wazuh-indexer:${WAZUH_VERSION:-4.7.0}"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms768m -Xmx768m
      # ⬇️ force demo security (admin/admin + self-signed certs)
      - DISABLE_INSTALL_DEMO_CONFIG=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add: [ "IPC_LOCK" ]
    volumes:
      - wazuh-indexer-data:/usr/share/opensearch/data
    networks:
      soc:
        aliases: [ "wazuh.indexer" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  wazuh-manager:
    image: "wazuh/wazuh-manager:${WAZUH_VERSION:-4.7.0}"
    environment:
      - OPENSEARCH_URL=https://wazuh.indexer:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_SSL_VERIFICATION=no
    volumes:
      - wazuh-manager-data:/var/ossec/data
    networks:
      soc:
        aliases: [ "wazuh.manager" ]
    depends_on:
      - wazuh-indexer
    ports:
      - "1514:1514/udp"
      - "55000:55000/tcp"

  wazuh-dashboard:
    image: "wazuh/wazuh-dashboard:${WAZUH_VERSION:-4.7.0}"
    environment:
      - OPENSEARCH_URL=https://wazuh.indexer:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=admin
      - OPENSEARCH_SSL_VERIFICATION=no
      - WAZUH_API_URL=https://wazuh.manager:55000
    networks:
      soc:
        aliases: [ "wazuh.dashboard" ]
    depends_on:
      - wazuh-manager
    ports:
      - "443:5601/tcp"
