# Minimal stack used ONLY during CI "test" job
version: "3.8"

networks:
  soc:
    driver: overlay
    attachable: true

volumes:
  wazuh-indexer-data:

services:
  wazuh-indexer:
    image: "wazuh/wazuh-indexer:${WAZUH_VERSION:-4.7.0}"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      # Small heap so it can start on tiny runners
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      # ✅ Disable the security plugin so startup doesn't block in CI
      - plugins.security.disabled=true
    ulimits:
      memlock: { soft: -1, hard: -1 }
      nofile:  { soft: 65536, hard: 65536 }
    cap_add: [ "IPC_LOCK" ]
    volumes:
      - wazuh-indexer-data:/usr/share/opensearch/data
    networks:
      soc:
        aliases: [ "wazuh.indexer" ]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
