version: "3.8"

networks:
  soc:
    driver: overlay
    attachable: true   # allow docker run to join this overlay during CI health checks

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:

services:
  wazuh-indexer:
    image: "wazuh/wazuh-indexer:${WAZUH_VERSION:-4.7.0}"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - wazuh-indexer-data:/usr/share/opensearch/data
    networks:
      soc:
        aliases:
          - wazuh.indexer
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10

  # One-shot bootstrap to initialize OpenSearch security index
  indexer-security-init:
    image: "wazuh/wazuh-indexer:${WAZUH_VERSION:-4.7.0}"
    networks:
      soc: {}
    depends_on:
      - wazuh-indexer
    deploy:
      restart_policy:
        condition: none
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        set -e
        echo "Waiting for wazuh-indexer:9200..."
        for i in $(seq 1 120); do
          if curl -sk -u admin:admin https://wazuh.indexer:9200/_cluster/health >/dev/null 2>&1; then
            break
          fi
          sleep 2
        done
        echo "Running securityadmin to initialize the security index..."
        SEC_BASE="/usr/share/wazuh-indexer"
        TOOL="$SEC_BASE/plugins/opensearch-security/tools/securityadmin.sh"
        CA="$SEC_BASE/config/root-ca.pem"
        CERT="$SEC_BASE/config/admin.pem"
        KEY="$SEC_BASE/config/admin-key.pem"
        CONF_DIR="$SEC_BASE/plugins/opensearch-security/securityconfig"
        if [ ! -f "$TOOL" ]; then
          echo "securityadmin tool not found at $TOOL"; exit 1
        fi
        if [ ! -f "$CA" ] || [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
          echo "Admin/CA certs not found under $SEC_BASE/config"; ls -l "$SEC_BASE/config" || true; exit 1
        fi
        bash "$TOOL" \
          -cd "$CONF_DIR" \
          -cacert "$CA" \
          -cert "$CERT" \
          -key "$KEY" \
          -icl -nhnv
        echo "Security index initialized successfully."
        true

  wazuh-manager:
    image: "wazuh/wazuh-manager:${WAZUH_VERSION:-4.7.0}"
    environment:
      - OPENSEARCH_URL=https://wazuh.indexer:9200
    volumes:
      - wazuh-manager-data:/var/ossec/data
    networks:
      soc:
        aliases:
          - wazuh.manager
    depends_on:
      - wazuh-indexer
    ports:
      - "1514:1514/udp"
      - "55000:55000/tcp"

  wazuh-dashboard:
    image: "wazuh/wazuh-dashboard:${WAZUH_VERSION:-4.7.0}"
    environment:
      - OPENSEARCH_URL=https://wazuh.indexer:9200
      - WAZUH_API_URL=https://wazuh.manager:55000
    networks:
      soc:
        aliases:
          - wazuh.dashboard
    depends_on:
      - wazuh-manager
    ports:
      - "443:5601/tcp"
