version: '3.8'
services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.0
    deploy: { replicas: 1 }
    volumes:
      - indexer-data:/var/lib/wazuh-indexer

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    deploy: { replicas: 1 }
    ports:
      - "1514:1514/udp"
      - "55000:55000"
    volumes:
      - manager-data:/var/ossec/data

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    deploy: { replicas: 1 }
    ports:
      - "443:5601"

volumes:
  indexer-data:
  manager-data:
