version: "3.8"

networks:
  wazuh-net:
    driver: overlay
    attachable: true

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.7.0
    networks: [wazuh-net]
    # simple readiness check so dashboard waits
    healthcheck:
      test: ["CMD-SHELL", "curl -sk https://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    deploy:
      replicas: 1

  wazuh-manager:
    image: wazuh/wazuh-manager:4.7.0
    networks: [wazuh-net]
    deploy:
      replicas: 1

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.7.0
    ports:
      - "443:5601"
    networks: [wazuh-net]
    environment:
      # Use the Swarm FQDN of the indexer service:
      OPENSEARCH_HOSTS: '["https://wazuh-test_wazuh-indexer:9200"]'
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_SSL_VERIFICATIONMODE: "none"   # demo only
      # Optional but harmless:
      OPENSEARCH_REQUESTHEADERSWHITELIST: '["securitytenant","Authorization"]'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 2m
