name: Wazuh SOC CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  WAZUH_VERSION: 4.7.0

jobs:
  # ──────────────────────────────
  # 1) Build and Trivy scan
  # ──────────────────────────────
  build-and-scan:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build custom image if you have a Dockerfile; otherwise pull the official one
      - name: Build or pull Wazuh Manager image
        id: build
        run: |
          set -e
          if [ -f "docker/wazuh-manager/Dockerfile" ]; then
            docker build -t wazuh-manager:${{ github.sha }} docker/wazuh-manager/
          else
            docker pull wazuh/wazuh-manager:${WAZUH_VERSION}
            docker tag wazuh/wazuh-manager:${WAZUH_VERSION} wazuh-manager:${{ github.sha }}
          fi

      - name: Prep disk space for Trivy
        run: |
          docker system prune -af || true
          mkdir -p "$HOME/.cache/trivy" "$HOME/.cache/trivy/tmp"
          df -h

      # First run downloads DB (no --skip-db-update); we use GHCR mirror, long timeout, and retries
      - name: Run Trivy vulnerability scanner
        run: |
          set -e
          CACHE_DIR="$HOME/.cache/trivy"
          DB_REPO="ghcr.io/aquasecurity/trivy-db:2"
          TIMEOUT="30m"
          export TMPDIR="$CACHE_DIR/tmp"
          mkdir -p "$TMPDIR"

          for i in 1 2 3; do
            trivy image \
              --scanners vuln \
              --cache-dir "$CACHE_DIR" \
              --db-repository "$DB_REPO" \
              --timeout "$TIMEOUT" \
              --severity CRITICAL,HIGH \
              --exit-code 1 \
              --format json \
              --output trivy-report.json \
              wazuh-manager:${{ github.sha }} && break || sleep 20
          done

      - name: Fetch Trivy HTML template
        if: always()
        run: curl -fsSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

      - name: Generate Trivy HTML Report
        if: always()
        continue-on-error: true
        run: |
          CACHE_DIR="$HOME/.cache/trivy"
          DB_REPO="ghcr.io/aquasecurity/trivy-db:2"
          TIMEOUT="30m"
          export TMPDIR="$CACHE_DIR/tmp"

          trivy image \
            --scanners vuln \
            --cache-dir "$CACHE_DIR" \
            --db-repository "$DB_REPO" \
            --timeout "$TIMEOUT" \
            --severity CRITICAL,HIGH \
            --format template \
            --template "@html.tpl" \
            --output trivy-report.html \
            wazuh-manager:${{ github.sha }}

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html

  # ──────────────────────────────
# 2) Spin test stack + run Selenium
# ──────────────────────────────
  test:
    runs-on: [self-hosted, linux, x64]
    needs: build-and-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure this runner can use Docker and Swarm is ready
      - name: Ensure Docker is usable & init Swarm
        run: |
          docker version
          docker info
          docker swarm init || true

      - name: Deploy temporary test stack
        run: |
          STACK=wazuh-test
          docker stack deploy -c stack/wazuh-stack.yml $STACK
          echo "Waiting for services to start…"
          # wait for services to have desired replicas
          for i in {1..60}; do
            READY=$(docker stack services $STACK --format '{{.Replicas}}' | awk -F/ '$1==$2' | wc -l)
            TOTAL=$(docker stack services $STACK --format '{{.Replicas}}' | wc -l)
            echo "Services ready: $READY/$TOTAL"
            [ "$READY" = "$TOTAL" ] && break || sleep 5
          done

      # Only proceed once the dashboard is really up on 443
      - name: Wait for Wazuh dashboard on https://localhost:443
        run: |
          for i in {1..60}; do
            if curl -skf https://localhost:443 >/dev/null; then
              echo "✅ Dashboard is up"
              exit 0
            fi
            echo "Still waiting... ($i/60)"
            docker stack services wazuh-test || true
            sleep 5
          done
          echo "❌ Dashboard did not become ready in time"
          docker service ps wazuh-test_wazuh-dashboard || true
          exit 1

      # System deps for Selenium (Chromium + chromedriver)
      - name: Install Chromium & chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver || true
          which chromedriver || true

      - name: Create Python venv & install test deps
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install selenium pytest pytest-html webdriver-manager

      - name: Run Selenium tests
        run: |
          source .venv/bin/activate
          pytest tests/selenium/test_dashboard.py -v --html=selenium-report.html

      - name: Upload Selenium report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: selenium-report.html

      - name: Cleanup test stack
        if: always()
        run: |
          docker stack rm wazuh-test
          # give it a moment to go away; ignore errors
          for i in {1..30}; do
            docker stack ps wazuh-test >/dev/null 2>&1 || break
            sleep 2
          done
          docker system prune -af --volumes || true


  # ──────────────────────────────
  # 3) Deploy to Swarm with Ansible (main branch pushes only)
  # ──────────────────────────────
  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: [build-and-scan, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Ensure you've created repo secret ANSIBLE_VAULT_PASSWORD
      - name: Configure Ansible vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

      - name: Ensure Docker Swarm initialized
        run: docker swarm init || true

      # Ansible must already be installed on the self-hosted runner
      - name: Deploy via Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory/production.yml \
            --vault-password-file .vault_pass \
            -e "image_tag=${{ github.sha }}" \
            ansible/playbooks/deploy.yml

      - name: Verify deployment
        run: |
          docker stack services wazuh-soc
          python3 tests/api/health_check.py

      - name: Cleanup sensitive files
        if: always()
        run: rm -f .vault_pass
