name: mini-soc-ci

on:
  push:
    branches: [ main, master ]
  pull_request:

env:
  WAZUH_VERSION: "4.7.0"

jobs:
  build-and-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Quick static check (placeholder)
        run: |
          echo "Build & scan step placeholder"
          # put your real build/scan here

  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set kernel params for OpenSearch
        shell: bash
        run: |
          set -euo pipefail
          echo "vm.max_map_count=262144" | sudo tee /etc/sysctl.d/99-wazuh.conf
          sudo sysctl -p /etc/sysctl.d/99-wazuh.conf || sudo sysctl -w vm.max_map_count=262144

      - name: Ensure Docker is usable & init Swarm
        shell: bash
        run: |
          set -euo pipefail
          sudo docker info >/dev/null
          # init if not already part of a swarm
          sudo docker node ls >/dev/null 2>&1 || sudo docker swarm init --advertise-addr 127.0.0.1 || true

      - name: Deploy temporary test stack (no host ports, demo security)
        shell: bash
        run: |
          set -euo pipefail
          sudo docker stack deploy -c stack/wazuh-stack-test-secure.yml wazuh-test

      - name: Wait for Wazuh Indexer (OpenSearch) to become healthy
        shell: bash
        timeout-minutes: 20
        run: |
          set -euo pipefail
          ATTEMPTS=60
          SLEEP=20
          for i in $(seq 1 "$ATTEMPTS"); do
            echo "[$i/$ATTEMPTS] Checking OpenSearch health..."
            # run curl *inside the Swarm overlay network*
            OUT=$(sudo docker run --rm --network wazuh-test_soc curlimages/curl:8.9.1 \
                  -sk -u admin:admin https://wazuh.indexer:9200/_cluster/health || true)
            echo "$OUT"
            # consider yellow or green as healthy for CI
            if echo "$OUT" | grep -q '"status":"green"\|"status":"yellow"'; then
              echo "OpenSearch is healthy enough (yellow/green)."
              exit 0
            fi
            sleep "$SLEEP"
          done
          echo "OpenSearch did not become healthy in time"
          exit 1

      - name: Basic API sanity checks (optional)
        shell: bash
        run: |
          set -euo pipefail
          sudo docker run --rm --network wazuh-test_soc curlimages/curl:8.9.1 \
            -sk -u admin:admin https://wazuh.indexer:9200
          sudo docker run --rm --network wazuh-test_soc curlimages/curl:8.9.1 \
            -sk -u admin:admin https://wazuh.indexer:9200/_cat/indices

      - name: Cleanup test stack
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          sudo docker stack rm wazuh-test || true
          # wait for services to disappear to avoid leaking networks/volumes between jobs
          for i in $(seq 1 30); do
            if ! sudo docker stack services wazuh-test >/dev/null 2>&1; then
              echo "Stack removed."
              break
            fi
            sleep 2
          done

  # keep your existing deploy job as-is; nothing here needs ports for test
  deploy:
    needs: [ build-and-scan, test ]
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Placeholder deploy
        run: |
          echo "Your real deployment steps go here (Ansible, etc.)"
