name: Wazuh SOC CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  WAZUH_VERSION: 4.7.0

jobs:
  build-and-scan:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build or pull Wazuh Manager image
        id: build
        run: |
          set -e
          if [ -f "docker/wazuh-manager/Dockerfile" ]; then
            docker build -t wazuh-manager:${{ github.sha }} docker/wazuh-manager/
          else
            docker pull wazuh/wazuh-manager:${WAZUH_VERSION}
            docker tag wazuh/wazuh-manager:${WAZUH_VERSION} wazuh-manager:${{ github.sha }}
          fi

      - name: Prep disk space for Trivy
        run: |
          docker system prune -af || true
          mkdir -p "$HOME/.cache/trivy" "$HOME/.cache/trivy/tmp"
          df -h

      - name: Fetch Trivy HTML template
        run: curl -fsSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/html.tpl -o html.tpl

      - name: Run Trivy vulnerability scanner (Docker engine → HTML)
        run: |
          set -euo pipefail
          CACHE_DIR="$HOME/.cache/trivy"
          DB_REPO="ghcr.io/aquasecurity/trivy-db:2"
          TIMEOUT="20m"
          mkdir -p "$CACHE_DIR"

          if ! docker image inspect wazuh-manager:${{ github.sha }} >/dev/null 2>&1; then
            docker pull wazuh/wazuh-manager:${WAZUH_VERSION}
            docker tag  wazuh/wazuh-manager:${WAZUH_VERSION}  wazuh-manager:${{ github.sha }}
          fi

          trivy image \
            --docker-host "unix:///var/run/docker.sock" \
            --scanners vuln \
            --cache-dir "$CACHE_DIR" \
            --db-repository "$DB_REPO" \
            --timeout "$TIMEOUT" \
            --severity CRITICAL,HIGH \
            --exit-code 1 \
            --format template --template "@html.tpl" \
            --output trivy-report.html \
            wazuh-manager:${{ github.sha }}

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-report.html

  test:
    runs-on: [self-hosted, linux, x64]
    needs: build-and-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set kernel params for OpenSearch
        run: |
          sudo sysctl -w vm.max_map_count=262144
          sudo sysctl -w fs.file-max=65536

      - name: Ensure Docker is usable & init Swarm
        run: |
          docker version
          docker info
          docker swarm init || true

      - name: Deploy temporary test stack
        run: |
          set -euo pipefail
          STACK=wazuh-test
          docker stack deploy -c stack/wazuh-stack.yml "$STACK"

          echo "Waiting for services to reach desired replicas…"
          for i in {1..120}; do
            READY=$(docker stack services "$STACK" --format '{{.Replicas}}' | awk -F/ '$1==$2' | wc -l)
            TOTAL=$(docker stack services "$STACK" --format '{{.Replicas}}' | wc -l)
            echo "Services ready: $READY/$TOTAL"
            [ "$READY" = "$TOTAL" ] && break || sleep 5
          done

      # Wait for indexer to reach >= yellow instead of plain HTTP 200
      - name: Wait for OpenSearch health (inside Swarm network)
        run: |
          set -e
          STACK=wazuh-test
          NET="${STACK}_soc"

          echo "Probing cluster health (target: >= yellow)…"
          for i in {1..60}; do
            OUT=$(docker run --rm --network "$NET" curlimages/curl:8.10.1 \
                    -sk -u admin:admin -w '\n%{http_code}' \
                    'https://wazuh.indexer:9200/_cluster/health?wait_for_status=yellow&timeout=30s' || true)
            CODE=$(echo "$OUT" | tail -n1)
            BODY=$(echo "$OUT" | sed '$d')

            echo "OpenSearch HTTP: $CODE"
            if [ "$CODE" = "200" ]; then
              echo "$BODY"
              exit 0
            fi

            docker service ls
            sleep 10
          done

          echo "OpenSearch did not become healthy in time"
          docker service ps ${STACK}_wazuh-indexer --no-trunc || true
          docker service logs --raw --timestamps ${STACK}_wazuh-indexer | tail -n 200 || true
          exit 1

      - name: Wait for Wazuh dashboard on https://localhost:443
        run: |
          for i in {1..120}; do
            if curl -skf https://localhost:443 >/dev/null; then
              echo "✅ Dashboard is up"; exit 0
            fi
            echo "Still waiting… ($i/120)"
            docker stack services wazuh-test || true
            sleep 5
          done
          echo "❌ Dashboard did not become ready in time"
          docker service ps wazuh-test_wazuh-dashboard || true
          docker service logs --raw --timestamps wazuh-test_wazuh-dashboard | tail -n 200 || true
          exit 1

      - name: Install Chromium & chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver || true
          which chromedriver || true

      - name: Create Python venv & install test deps
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install selenium pytest pytest-html webdriver-manager

      - name: Run Selenium tests
        run: |
          source .venv/bin/activate
          pytest tests/selenium/test_dashboard.py -v --html=selenium-report.html

      - name: Upload Selenium report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-report
          path: selenium-report.html

      - name: Cleanup test stack
        if: always()
        run: |
          STACK=wazuh-test
          docker stack rm "$STACK" || true
          for i in {1..30}; do
            docker stack ps "$STACK" >/dev/null 2>&1 || break
            sleep 2
          done
          docker system prune -af --volumes || true

  deploy:
    runs-on: [self-hosted, linux, x64]
    needs: [build-and-scan, test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Ansible vault password
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

      - name: Ensure Docker Swarm initialized
        run: docker swarm init || true

      - name: Deploy via Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory/production.yml \
            --vault-password-file .vault_pass \
            -e "image_tag=${{ github.sha }}" \
            ansible/playbooks/deploy.yml

      - name: Verify deployment
        run: |
          docker stack services wazuh-soc
          python3 tests/api/health_check.py

      - name: Cleanup sensitive files
        if: always()
        run: rm -f .vault_pass
